Kovalenko: lesson04
JD2-86/practice-jd2-86 pull request #52
Opened 2021-12-19 11:21 UTC by alexkoval6030

close: #21

2021-12-22 07:24 UTC, rakovets requested changes
You need to remove build artifacts (directory^ `target`).

2021-12-22 07:24 UTC, rakovets commented on kovalenko/lesson04/web-CV/pom.xml
> +</project>
"Violation: POSIX standard defines a line: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
Solution: Add terminating <newline>"

2021-12-22 07:24 UTC, rakovets commented on kovalenko/lesson04/web-CV/src/main/webapp/WEB-INF/web.xml
> +</web-app>
"Violation: POSIX standard defines a line: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
Solution: Add terminating <newline>"

2021-12-22 07:24 UTC, rakovets commented on kovalenko/lesson04/web-CV/src/main/webapp/resources/css/style.css
> +}
"Violation: POSIX standard defines a line: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
Solution: Add terminating <newline>"

2021-12-22 22:04 UTC, alexkoval6030 commented on kovalenko/lesson04/web-CV/pom.xml
> +</project>
correct

2021-12-22 22:05 UTC, alexkoval6030 commented on kovalenko/lesson04/web-CV/src/main/webapp/WEB-INF/web.xml
> +</web-app>
correct

2021-12-22 22:05 UTC, alexkoval6030 commented on kovalenko/lesson04/web-CV/src/main/webapp/resources/css/style.css
> +}
correct

2021-12-23 07:37 UTC, rakovets approved these changes
Approved

2021-12-23 07:38 UTC, merged