Shcharbunou: lesson04
JD2-86/practice-jd2-86 pull request #65
Opened 2021-12-19 18:47 UTC by ddshcharbunou

close: #39

2021-12-19 18:50 UTC, ddshcharbunou commented
second commit is mistake

2021-12-22 07:17 UTC, rakovets requested changes
You need to return removed files.

2021-12-22 07:17 UTC, rakovets commented on shcharbunou/lesson04/maven-webapp-shcharbunouCV/src/main/webapp/style.css
> +}
"Violation: POSIX standard defines a line: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206
Solution: Add terminating <newline>"

2021-12-22 09:21 UTC, ddshcharbunou commented
fixed

2021-12-24 14:52 UTC, closed without merging