Karpovich: lesson04
JD2-86/practice-jd2-86 pull request #71
Opened 2021-12-20 14:07 UTC by sablayz

close: #15

2021-12-22 07:26 UTC, rakovets requested changes
You need to add more content

2021-12-22 07:26 UTC, rakovets commented on karpovich-v/lesson04/src/main/webapp/index.jsp
> +</body>
You need to add more content

2021-12-22 14:07 UTC, sablayz commented on karpovich-v/lesson04/src/main/webapp/index.jsp
> +</body>
done

2021-12-23 07:10 UTC, rakovets approved these changes
Approved

2021-12-23 07:11 UTC, merged